{{- $clusterSet := .Values.global.clusterSetName | default "resilient" }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  labels:
    cluster.open-cluster-management.io/backup: resource
  name: mirrorpeer-{{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  items:
  - clusterName: {{ .Values.global.primaryClusterName }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ .Values.global.secondaryClusterName }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  type: async
