{{- if eq "1" (include "rdr.ramenResourcesEnabled" .) }}
{{- $drpc := .Values.drpc | default dict }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
    drplacementcontrol.ramendr.openshift.io/drpc-name: {{ $drpc.name | default "gitops-vm-protection" }}
    drplacementcontrol.ramendr.openshift.io/drpc-namespace: {{ $drpc.namespace | default "openshift-dr-ops" }}
    argocd.argoproj.io/sync-wave: "8"
  name: {{ index $drpc "placementRef" "name" | default "gitops-vm-protection-placement-1" }}
  namespace: {{ index $drpc "placementRef" "namespace" | default "openshift-dr-ops" }}
spec:
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
{{- end }}
